[package]
name = "thex"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]

[dependencies]
rocket = "0.3"
rocket_codegen = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rocket_contrib = { version = "0.3", default-features = false, features = ["json"] }
